services:
  postgres:
    image: "postgres:17.2-alpine3.21"
    env_file:
      - ../.env
    ports:
      - "5432:5432"
  mongodb:
    image: mongo:5.0
    restart: awlays
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # UI do RabbitMQ

  user_service:
    build: ./user-service
    ports:
      - "3001:3000"
    depends_on:
      - postgres

  campaign_service:
    build: ./campaign-service
    ports:
      - "3002:3000"
    depends_on:
      - postgres
      - rabbitmq

  media_service:
    build: ./media-service
    ports:
      - "3003:3000"
    depends_on:
      - mongodb

  notification_service:
    build: ./notification-service
    ports:
      - "3004:3000"
    depends_on:
      - rabbitmq

  api_gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user_service
      - campaign_service
      - media_service
      - notification_service